package drift

import (
	"bytes"
	"fmt"
	"html/template"
)

const htmlTemplate = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Terraxi Drift Report</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 960px; margin: 40px auto; padding: 0 20px; color: #333; }
  h1 { color: #1a1a2e; }
  h2 { color: #16213e; border-bottom: 2px solid #e2e8f0; padding-bottom: 8px; }
  .summary { display: flex; gap: 20px; margin: 20px 0; }
  .card { padding: 20px; border-radius: 8px; flex: 1; text-align: center; }
  .card-managed { background: #d4edda; color: #155724; }
  .card-unmanaged { background: #fff3cd; color: #856404; }
  .card-deleted { background: #f8d7da; color: #721c24; }
  .card h3 { margin: 0; font-size: 2em; }
  .card p { margin: 4px 0 0; }
  table { width: 100%%; border-collapse: collapse; margin: 16px 0; }
  th, td { padding: 8px 12px; text-align: left; border-bottom: 1px solid #e2e8f0; }
  th { background: #f7fafc; font-weight: 600; }
  tr:hover { background: #f1f5f9; }
  .empty { color: #999; font-style: italic; padding: 20px; }
  footer { margin-top: 40px; color: #999; font-size: 0.85em; }
</style>
</head>
<body>
<h1>Terraxi Drift Report</h1>

<div class="summary">
  <div class="card card-managed"><h3>{{len .Managed}}</h3><p>Managed</p></div>
  <div class="card card-unmanaged"><h3>{{len .Unmanaged}}</h3><p>Unmanaged</p></div>
  <div class="card card-deleted"><h3>{{len .Deleted}}</h3><p>Deleted</p></div>
</div>

{{if .Unmanaged}}
<h2>Unmanaged Resources</h2>
<p>Resources found in the cloud but not tracked in Terraform state.</p>
<table>
<tr><th>Type</th><th>ID</th><th>Name</th><th>Region</th></tr>
{{range .Unmanaged}}<tr><td>{{.Type}}</td><td>{{.ID}}</td><td>{{.Name}}</td><td>{{.Region}}</td></tr>
{{end}}</table>
{{else}}
<h2>Unmanaged Resources</h2>
<p class="empty">No unmanaged resources found.</p>
{{end}}

{{if .Deleted}}
<h2>Deleted Resources</h2>
<p>Resources tracked in state but no longer found in the cloud.</p>
<table>
<tr><th>Type</th><th>Address</th><th>ID</th></tr>
{{range .Deleted}}<tr><td>{{.Type}}</td><td>{{.Address}}</td><td>{{.ID}}</td></tr>
{{end}}</table>
{{else}}
<h2>Deleted Resources</h2>
<p class="empty">No deleted resources found.</p>
{{end}}

<footer>Generated by <a href="https://github.com/atoolz/terraxi">Terraxi</a></footer>
</body>
</html>`

// RenderHTML generates a self-contained HTML drift report.
func RenderHTML(report *DriftReport) ([]byte, error) {
	tmpl, err := template.New("drift").Parse(htmlTemplate)
	if err != nil {
		return nil, fmt.Errorf("parsing HTML template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, report); err != nil {
		return nil, fmt.Errorf("rendering HTML report: %w", err)
	}

	return buf.Bytes(), nil
}
